# Generated by Django 5.0.4 on 2024-04-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mystore', '0002_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mystore.products')),
                ('thecart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carts.cartmodel')),
            ],
        ),
    ]
