# Generated by Django 5.0.4 on 2024-04-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartmodel',
            new_name='Thecart',
        ),
    ]
