# Generated by Django 5.0.4 on 2024-04-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0002_rename_cartmodel_thecart'),
        ('Mystore', '0005_rename_variations_variation_alter_variation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Mystore.variation'),
        ),
    ]
