# Generated by Django 5.0.4 on 2024-04-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
