# Generated by Django 5.0.4 on 2024-04-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mystore', '0004_alter_variations_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='variations',
            new_name='variation',
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={},
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='theproduct',
            new_name='product',
        ),
    ]
