# Generated by Django 5.0.3 on 2024-04-14 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mystore', '0006_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='store/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mystore.products')),
            ],
        ),
    ]
