# Generated by Django 5.0.3 on 2024-04-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mystore', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
