# Generated by Django 5.0.4 on 2024-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_remove_order_countrydropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
